### ISSUE TITLE
Meeting Agenda Jan 14 2021

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/gdphelper#17]
1. Confirming Milestone 1 deliverables
2. Function Naming Conventions
3. ? Add any other items below

**Comment by gfairbro** [comment]
Discuss inputs/outputs
Discuss rebasing branches

**Comment by aldojasb** [comment]
Great! Nothing to add so far :)

**Comment by gfairbro** [comment]
Discussed the above points, agreed on a naming convention of 'gdp'+verb for functions. 
Ramiro volunteered to improve our contributing framework somewhat. 
Discussed extracting the data title from the metadata in script 1, and returning a data frame as well. 
Confirmed Pull Request responisibilities and merge process.
