### ISSUE TITLE
Generalizing for different datasets

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/gdphelper#49]
Hey team, i think we need to discuss a bit about how to handle the different data sets that we are trying to generalize for. Currently i have defined the cleaned data frame to have 5 columns but i think Location is not going to work because some of the data is not separated by location, e.g. https://open.canada.ca/data/en/dataset/9f2116fc-265a-419f-a921-2d747c039f34

I am going to start working through the spreadsheets looking for divergence. i will keep this issue updated. I would suggest not getting too deep in the weeds with gdpdescribe and gdpplotter until i have this better defined.

**Comment by gfairbro** [comment]
[package_tinker (1).pdf](https://github.com/UBC-MDS/gdphelper/files/7901040/package_tinker.1.pdf)

Here is the list of the current files and undecided columns.

**Comment by RamiroMejia** [comment]
thanks Gabe. Let's talk about the column names tomorrow. I want to change the defaults of my function

**Comment by gfairbro** [comment]
OK the latest version of gdpcleaner accounts for different possible column names and delineates which ones will be available in it's docstring, which should help @RamiroMejia and @aldojasb get creative with how they choose to render, whether they test for columns or just accept an argument to manipulate outputs.
