### ISSUE TITLE
gdpimporter: File Cleanup

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/gdphelper#50]
Hey Gloria, i noticed in my data exploration that the importer doesnt delete the initial file download, which i think it should do, or otherwise manage the original downloaded files. What do you think?

**Comment by GloriaWYY** [comment]
Do you mean the `.zip` or the unzipped `.csv` file? I think deleting `.zip` would be reasonable, but we should keep `.csv` since `gdpimporter` can potentially rename the data `.csv` when optional `filename` is supplied. I will look into deleting `.zip` 😺

**Comment by gfairbro** [comment]
Yeah the zip and the Metadata file. here is my working folder when i batch through the links 😆 
![image](https://user-images.githubusercontent.com/88786321/150235250-38ec66f9-e855-43c1-a3cc-2ac32950f058.png)

**Comment by GloriaWYY** [comment]
🚀 Fixed in #52
