### ISSUE TITLE
Function #1 - Data Importer

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/gdphelper#6]
This function will import data regardless of separator, separator can be passed as argument, can take a URL or local file, and can save to a local file. Can also potentially handle binary files.

**Comment by gfairbro** [comment]
Gloria I think it would be useful if your function extracted the name of the data set and returned it along with a DataFrame, or added it to the dataframe. The name is found in cell 2, 1 of the Metadata. We can pass this along all the functions so that we have a consistent Title and can easily tie it back to the data source.

**Comment by GloriaWYY** [comment]
Changes incorporated in PR #13
