### ISSUE TITLE
License Selection Discussion

### ISSUE THREAD

**Issue by gfairbro** [UBC-MDS/gdphelper#89]
Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license.

**Comment by GloriaWYY** [comment]
Right now we have MIT LICENSE for both Python and R packages. Let's discuss whether we should keep it or switch to a new one!

I remembered Tiffany mentioned it is easier to switch from a more restrictive LICENSE to a more open one (if necessary) than the reverse. But I am okay with MIT LICENSE for its simplicity, and I think this should be sufficient for our package, and I am willing to put it public and make it easiest for people to use and adapt it. What do you guys think?

One thing we should not forget is to add our names to the R package LICENSE (right now it just says `gdphelperR authors`)

**Comment by gfairbro** [comment]
Hey team, I don't feel terribly strongly about it, but i think it might be worth discussing moving to the GNU license as well, to help support open source.

**Comment by gfairbro** [comment]
Also i updated the authors in the R package and removed the second License skeleton

**Comment by GloriaWYY** [comment]
> Also i updated the authors in the R package and removed the second License skeleton

Since R cmd check was unhappy about removing that `LICENSE`, I added it back.

**Comment by aldojasb** [comment]
Hi guys! I'm trying to make sense of the difference between the MIT license and the GNU haha If I'm not mistaken, the MIT license is a sort of  “permissive licenses”. In other words, this license says  “do whatever you want with this, just don’t sue me.” And, the general idea of GNU license is “if you make a derivative work of this, and distribute it to others under certain circumstances, then you have to provide the source code under this license.” Does it make sense for you too?

**Comment by gfairbro** [comment]
Yeah the core difference is just that it prevents our source from being used in a closed source project after publication. or really under any other license - the new project would also have to be published under the GNU license.

**Comment by GloriaWYY** [comment]
Yes, the MIT license is the most unrestricted one. 

A few reasons I think it is appropriate for our packages:

- We are not seeking profits from `gdphelper` and `gdphelperR` and so using an MIT license relieves us from legal matters.
- It gives the users the highest degree of freedom to use and adapt the functions, which is my hope while developing these packages. 

If we all agree on these, we can finalize our decision on license choice 🥇

**Comment by RamiroMejia** [comment]
I've been checking the different types of licenses, I agree with Gloria. Let's use MIT license.

**Comment by gfairbro** [comment]
Works for me lets leave MIT License in place. @aldojasb ?

**Comment by aldojasb** [comment]
Yes, it works for me too. Let's go with MIT License :)
